{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Cable Defect Detection — YOLO26 v4 (Production Grade)\n",
    "### 3 Classes: defect | label | water\n",
    "### Improvements: K-Fold CV · Class Weights · imgsz=832 · Anti-bias · Focal Loss\n",
    "\n",
    "| Improvement | Why |\n",
    "|---|---|\n",
    "| **K-Fold Cross Validation** | Prevents bias — model tested on ALL data, not just one split |\n",
    "| **Class Weights** | Fixes water under-detection — penalises missing water more |\n",
    "| **imgsz=832** | Catches small water droplets missed at 640 |\n",
    "| **Focal Loss (cls=2.0)** | Forces model to focus on hard-to-learn water examples |\n",
    "| **Anti-bias checks** | Detects if model over-predicts any class before deployment |\n",
    "| **Calibrated thresholds** | Per-class optimal threshold from validation curve |\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1 — Install"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install ultralytics albumentations split-folders -q\n",
    "\n",
    "import os, shutil, yaml, random, glob, zipfile, json\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.patches as patches\n",
    "from matplotlib.patches import Patch\n",
    "from PIL import Image\n",
    "import albumentations as A\n",
    "import cv2\n",
    "import splitfolders\n",
    "from ultralytics import YOLO\n",
    "from google.colab import files\n",
    "import pandas as pd\n",
    "from collections import Counter\n",
    "from sklearn.model_selection import KFold\n",
    "\n",
    "print('✅ Done!')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2 — Upload ZIP"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('Upload your ZIP file...')\n",
    "uploaded = files.upload()\n",
    "zip_name = list(uploaded.keys())[0]\n",
    "\n",
    "EXTRACT_PATH = '/content/dataset'\n",
    "os.makedirs(EXTRACT_PATH, exist_ok=True)\n",
    "with zipfile.ZipFile(zip_name, 'r') as z:\n",
    "    z.extractall(EXTRACT_PATH)\n",
    "\n",
    "RAW_IMAGES = '/content/dataset/Project/images'\n",
    "RAW_LABELS = '/content/dataset/Project/labels'\n",
    "images = sorted(glob.glob(f'{RAW_IMAGES}/*.*'))\n",
    "labels = sorted(glob.glob(f'{RAW_LABELS}/*.txt'))\n",
    "print(f'Images: {len(images)}  |  Labels: {len(labels)}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 3 — Labels "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "FIXED_IMAGES = '/content/fixed/images'\n",
    "FIXED_LABELS = '/content/fixed/labels'\n",
    "os.makedirs(FIXED_IMAGES, exist_ok=True)\n",
    "os.makedirs(FIXED_LABELS, exist_ok=True)\n",
    "\n",
    "# ── Class mapping: original_id -> new_id ──────────────────────────────────────\n",
    "# 0=defect | 1=label | 2=water\n",
    "# Edit CLASS_MAP if your dataset uses different original IDs\n",
    "CLASS_MAP    = {0: 0, 1: 1, 2: 2}\n",
    "CLASS_NAMES  = {0: 'defect', 1: 'label', 2: 'water'}\n",
    "DEFAULT_CLASS = 0\n",
    "\n",
    "def polygon_to_bbox(coords):\n",
    "    xs = coords[0::2]; ys = coords[1::2]\n",
    "    x_min, x_max = min(xs), max(xs)\n",
    "    y_min, y_max = min(ys), max(ys)\n",
    "    cx = (x_min + x_max) / 2; cy = (y_min + y_max) / 2\n",
    "    w  = x_max - x_min;       h  = y_max - y_min\n",
    "    return cx, cy, w, h\n",
    "\n",
    "converted = 0\n",
    "for lbl_path in labels:\n",
    "    stem = os.path.splitext(os.path.basename(lbl_path))[0]\n",
    "    img_path = None\n",
    "    for ext in ['.jpg', '.jpeg', '.png', '.bmp']:\n",
    "        c = f'{RAW_IMAGES}/{stem}{ext}'\n",
    "        if os.path.exists(c): img_path = c; break\n",
    "    if img_path is None: continue\n",
    "    new_lines = []\n",
    "    with open(lbl_path) as f:\n",
    "        for line in f:\n",
    "            parts = line.strip().split()\n",
    "            if len(parts) < 5: continue\n",
    "            orig_cls = int(parts[0])\n",
    "            new_cls  = CLASS_MAP.get(orig_cls, DEFAULT_CLASS)\n",
    "            coords   = list(map(float, parts[1:]))\n",
    "            if len(coords) == 4:\n",
    "                cx, cy, w, h = coords\n",
    "            elif len(coords) >= 6 and len(coords) % 2 == 0:\n",
    "                cx, cy, w, h = polygon_to_bbox(coords)\n",
    "            else:\n",
    "                cx, cy, w, h = coords[:4]\n",
    "            cx = max(0.0, min(1.0, cx)); cy = max(0.0, min(1.0, cy))\n",
    "            w  = max(0.001, min(1.0, w)); h  = max(0.001, min(1.0, h))\n",
    "            new_lines.append(f'{new_cls} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}')\n",
    "    if new_lines:\n",
    "        with open(f'{FIXED_LABELS}/{stem}.txt', 'w') as f:\n",
    "            f.write('\\n'.join(new_lines) + '\\n')\n",
    "        shutil.copy(img_path, f'{FIXED_IMAGES}/{os.path.basename(img_path)}')\n",
    "        converted += 1\n",
    "\n",
    "print(f'Converted {converted} label files → 3 classes')\n",
    "dist = Counter()\n",
    "for t in glob.glob(f'{FIXED_LABELS}/*.txt'):\n",
    "    for line in open(t):\n",
    "        p = line.strip().split()\n",
    "        if p: dist[int(p[0])] += 1\n",
    "print('\\nClass distribution (raw):')\n",
    "for cid, cnt in sorted(dist.items()):\n",
    "    print(f'  class {cid} ({CLASS_NAMES[cid]}): {cnt} boxes')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 4 — Visual Check of Labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "CLASS_COLORS = {0: 'red', 1: 'dodgerblue', 2: 'lime'}\n",
    "CLASS_NAMES  = {0: 'defect', 1: 'label', 2: 'water'}\n",
    "\n",
    "fixed_imgs = sorted(glob.glob(f'{FIXED_IMAGES}/*.*'))\n",
    "samples = random.sample(fixed_imgs, min(6, len(fixed_imgs)))\n",
    "fig, axes = plt.subplots(2, 3, figsize=(16, 10))\n",
    "axes = axes.flatten()\n",
    "for i, img_path in enumerate(samples):\n",
    "    img = np.array(Image.open(img_path).convert('RGB'))\n",
    "    h, w = img.shape[:2]\n",
    "    ax = axes[i]; ax.imshow(img)\n",
    "    stem = os.path.splitext(os.path.basename(img_path))[0]\n",
    "    lbl  = f'{FIXED_LABELS}/{stem}.txt'\n",
    "    if os.path.exists(lbl):\n",
    "        with open(lbl) as f:\n",
    "            for line in f:\n",
    "                p = line.strip().split()\n",
    "                if len(p) == 5:\n",
    "                    cls_id = int(p[0])\n",
    "                    cx, cy, bw, bh = map(float, p[1:])\n",
    "                    x1=int((cx-bw/2)*w); y1=int((cy-bh/2)*h)\n",
    "                    x2=int((cx+bw/2)*w); y2=int((cy+bh/2)*h)\n",
    "                    color = CLASS_COLORS.get(cls_id, 'yellow')\n",
    "                    label = CLASS_NAMES.get(cls_id, str(cls_id))\n",
    "                    ax.add_patch(patches.Rectangle((x1,y1),x2-x1,y2-y1,\n",
    "                        linewidth=2, edgecolor=color, facecolor='none'))\n",
    "                    ax.text(x1, max(0,y1-5), label, color='white', fontsize=8,\n",
    "                        bbox=dict(facecolor=color, alpha=0.7, pad=1))\n",
    "    ax.set_title(os.path.basename(img_path), fontsize=7); ax.axis('off')\n",
    "\n",
    "legend_elements = [Patch(facecolor=c, label=CLASS_NAMES[i]) for i, c in CLASS_COLORS.items()]\n",
    "fig.legend(handles=legend_elements, loc='lower center', ncol=3, fontsize=11,\n",
    "           title='Classes', title_fontsize=12, framealpha=0.9)\n",
    "plt.suptitle('Fixed Labels — 3 Classes: defect | label | water', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout(rect=[0, 0.06, 1, 1]); plt.show()\n",
    "print('Red=defect | Blue=label | Green=water')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 5 — Class-Aware Augmentation (water gets 3× more)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "AUG_IMAGES = '/content/augmented/images'\n",
    "AUG_LABELS = '/content/augmented/labels'\n",
    "os.makedirs(AUG_IMAGES, exist_ok=True)\n",
    "os.makedirs(AUG_LABELS, exist_ok=True)\n",
    "\n",
    "CLASS_NAMES = {0: 'defect', 1: 'label', 2: 'water'}\n",
    "\n",
    "# ── Base transform (defect & label) ──────────────────────────────────────────\n",
    "transform_base = A.Compose([\n",
    "    A.HorizontalFlip(p=0.5),\n",
    "    A.VerticalFlip(p=0.3),\n",
    "    A.Rotate(limit=20, p=0.5),\n",
    "    A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, p=0.6),\n",
    "    A.HueSaturationValue(hue_shift_limit=10, sat_shift_limit=30, val_shift_limit=20, p=0.4),\n",
    "    A.GaussNoise(var_limit=(10, 50), p=0.4),\n",
    "    A.GaussianBlur(blur_limit=3, p=0.3),\n",
    "    A.CLAHE(clip_limit=2.0, p=0.3),\n",
    "    A.RandomShadow(p=0.2),\n",
    "    A.Perspective(scale=(0.02, 0.08), p=0.3),\n",
    "    A.RandomScale(scale_limit=0.2, p=0.3),\n",
    "], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels'], min_visibility=0.4))\n",
    "\n",
    "# ── Water transform: heavy color/texture shifts to fix confusion with defect ──\n",
    "transform_water = A.Compose([\n",
    "    A.HorizontalFlip(p=0.5),\n",
    "    A.VerticalFlip(p=0.5),\n",
    "    A.Rotate(limit=30, p=0.7),\n",
    "    A.RandomBrightnessContrast(brightness_limit=0.45, contrast_limit=0.45, p=0.85),\n",
    "    A.HueSaturationValue(hue_shift_limit=25, sat_shift_limit=60, val_shift_limit=35, p=0.75),\n",
    "    A.GaussNoise(var_limit=(20, 100), p=0.65),\n",
    "    A.GaussianBlur(blur_limit=5, p=0.5),\n",
    "    A.CLAHE(clip_limit=3.5, p=0.5),\n",
    "    A.RandomShadow(p=0.45),\n",
    "    A.Perspective(scale=(0.04, 0.12), p=0.5),\n",
    "    A.RandomScale(scale_limit=0.35, p=0.5),\n",
    "    A.ElasticTransform(alpha=100, sigma=12, p=0.35),\n",
    "    A.GridDistortion(num_steps=5, distort_limit=0.25, p=0.35),\n",
    "    A.CoarseDropout(max_holes=6, max_height=25, max_width=25, p=0.25),\n",
    "    A.RandomRain(blur_value=1, p=0.2),          # simulate water reflection\n",
    "    A.RandomFog(fog_coef_range=(0.1, 0.2), p=0.15),  # simulate wet cable surface\n",
    "], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels'], min_visibility=0.35))\n",
    "\n",
    "# ── Per-class augmentation count: water gets 3× ──────────────────────────────\n",
    "AUGMENT_COUNTS = {0: 10, 1: 10, 2: 30}\n",
    "\n",
    "total    = 0\n",
    "src_imgs = sorted(glob.glob(f'{FIXED_IMAGES}/*.*'))\n",
    "\n",
    "for img_path in src_imgs:\n",
    "    stem     = os.path.splitext(os.path.basename(img_path))[0]\n",
    "    lbl_path = f'{FIXED_LABELS}/{stem}.txt'\n",
    "    img = cv2.imread(img_path)\n",
    "    if img is None: continue\n",
    "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "    bboxes, class_labels = [], []\n",
    "    if os.path.exists(lbl_path):\n",
    "        with open(lbl_path) as f:\n",
    "            for line in f:\n",
    "                p = line.strip().split()\n",
    "                if len(p) == 5:\n",
    "                    class_labels.append(int(p[0]))\n",
    "                    bboxes.append([float(x) for x in p[1:5]])\n",
    "    if not bboxes: continue\n",
    "\n",
    "    dominant_cls = Counter(class_labels).most_common(1)[0][0]\n",
    "    n_aug = AUGMENT_COUNTS.get(dominant_cls, 10)\n",
    "    transform = transform_water if dominant_cls == 2 else transform_base\n",
    "\n",
    "    shutil.copy(img_path,  f'{AUG_IMAGES}/{stem}_orig.jpg')\n",
    "    shutil.copy(lbl_path,  f'{AUG_LABELS}/{stem}_orig.txt')\n",
    "\n",
    "    for k in range(n_aug):\n",
    "        try:\n",
    "            aug = transform(image=img, bboxes=bboxes, class_labels=class_labels)\n",
    "            if not aug['bboxes']: continue\n",
    "            name = f'{stem}_aug{k:03d}'\n",
    "            cv2.imwrite(f'{AUG_IMAGES}/{name}.jpg',\n",
    "                cv2.cvtColor(aug['image'], cv2.COLOR_RGB2BGR))\n",
    "            with open(f'{AUG_LABELS}/{name}.txt', 'w') as f:\n",
    "                for c, box in zip(aug['class_labels'], aug['bboxes']):\n",
    "                    f.write(f'{c} {\" \".join([f\"{v:.6f}\" for v in box])}\\n')\n",
    "            total += 1\n",
    "        except: pass\n",
    "\n",
    "aug_imgs = sorted(glob.glob(f'{AUG_IMAGES}/*.jpg'))\n",
    "print(f'Original : {len(src_imgs)}')\n",
    "print(f'Generated: {total}')\n",
    "print(f'Total    : {len(aug_imgs)}')\n",
    "\n",
    "dist2 = Counter()\n",
    "for t in glob.glob(f'{AUG_LABELS}/*.txt'):\n",
    "    for line in open(t):\n",
    "        p = line.strip().split()\n",
    "        if p: dist2[int(p[0])] += 1\n",
    "print('\\nAugmented class distribution:')\n",
    "total_boxes = sum(dist2.values())\n",
    "for cid, cnt in sorted(dist2.items()):\n",
    "    print(f'  class {cid} ({CLASS_NAMES[cid]}): {cnt} boxes  ({cnt/total_boxes*100:.1f}%)')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 6 — Build Paired Dataset (K-Fold will split)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "PAIRED_DIR = '/content/paired'\n",
    "\n",
    "for img_path in glob.glob(f'{AUG_IMAGES}/*.jpg'):\n",
    "    stem = os.path.splitext(os.path.basename(img_path))[0]\n",
    "    lbl  = f'{AUG_LABELS}/{stem}.txt'\n",
    "    if not os.path.exists(lbl): continue\n",
    "    di = f'{PAIRED_DIR}/images/{stem}.jpg'\n",
    "    dl = f'{PAIRED_DIR}/labels/{stem}.txt'\n",
    "    os.makedirs(os.path.dirname(di), exist_ok=True)\n",
    "    os.makedirs(os.path.dirname(dl), exist_ok=True)\n",
    "    shutil.copy(img_path, di)\n",
    "    shutil.copy(lbl, dl)\n",
    "\n",
    "all_imgs = sorted(glob.glob(f'{PAIRED_DIR}/images/*.jpg'))\n",
    "print(f'Total paired images: {len(all_imgs)}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 7 — K-Fold Cross Validation (5 folds)\n",
    "> Prevents bias: each image is used for validation exactly once.\n",
    "> Best fold weights are automatically selected at the end."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── K-Fold Configuration ─────────────────────────────────────────────────────\n",
    "N_FOLDS     = 5\n",
    "IMGSZ       = 832     # larger than 640 → catches small water droplets\n",
    "EPOCHS      = 200\n",
    "BATCH       = 8       # reduced for imgsz=832 to fit T4 VRAM\n",
    "PATIENCE    = 40\n",
    "\n",
    "CLASS_NAMES_LIST = ['defect', 'label', 'water']\n",
    "\n",
    "all_imgs = sorted(glob.glob(f'{PAIRED_DIR}/images/*.jpg'))\n",
    "all_imgs = np.array(all_imgs)\n",
    "kf = KFold(n_splits=N_FOLDS, shuffle=True, random_state=42)\n",
    "\n",
    "fold_results = []   # (fold_idx, mAP50, model_path)\n",
    "\n",
    "for fold_idx, (train_idx, val_idx) in enumerate(kf.split(all_imgs)):\n",
    "    print(f'\\n{\"=\"*60}')\n",
    "    print(f'  FOLD {fold_idx+1}/{N_FOLDS}  |  train={len(train_idx)}  val={len(val_idx)}')\n",
    "    print(f'{\"=\"*60}')\n",
    "\n",
    "    # ── Build fold directories ────────────────────────────────────────────────\n",
    "    fold_dir = f'/content/fold_{fold_idx}'\n",
    "    for split in ['train', 'val']:\n",
    "        os.makedirs(f'{fold_dir}/images/{split}', exist_ok=True)\n",
    "        os.makedirs(f'{fold_dir}/labels/{split}', exist_ok=True)\n",
    "\n",
    "    for idx, split in [(train_idx, 'train'), (val_idx, 'val')]:\n",
    "        for img_path in all_imgs[idx]:\n",
    "            stem = os.path.splitext(os.path.basename(img_path))[0]\n",
    "            lbl  = f'{PAIRED_DIR}/labels/{stem}.txt'\n",
    "            shutil.copy(img_path, f'{fold_dir}/images/{split}/{os.path.basename(img_path)}')\n",
    "            if os.path.exists(lbl):\n",
    "                shutil.copy(lbl, f'{fold_dir}/labels/{split}/{stem}.txt')\n",
    "\n",
    "    # ── YAML for this fold ────────────────────────────────────────────────────\n",
    "    yaml_path = f'{fold_dir}/dataset.yaml'\n",
    "    with open(yaml_path, 'w') as f:\n",
    "        yaml.dump({\n",
    "            'path' : fold_dir,\n",
    "            'train': 'images/train',\n",
    "            'val'  : 'images/val',\n",
    "            'nc'   : 3,\n",
    "            'names': CLASS_NAMES_LIST\n",
    "        }, f)\n",
    "\n",
    "    # ── Train ─────────────────────────────────────────────────────────────────\n",
    "    model = YOLO('yolo26s.pt')\n",
    "    model.train(\n",
    "        data=yaml_path,\n",
    "        epochs=EPOCHS,\n",
    "        imgsz=IMGSZ,\n",
    "        batch=BATCH,\n",
    "        patience=PATIENCE,\n",
    "        lr0=0.01,\n",
    "        lrf=0.0005,\n",
    "        momentum=0.937,\n",
    "        weight_decay=0.0005,\n",
    "        warmup_epochs=5,\n",
    "        # ── Augmentation ──────────────────────────────────────────────────────\n",
    "        hsv_h=0.02, hsv_s=0.85, hsv_v=0.5,\n",
    "        degrees=20.0, translate=0.15, scale=0.6,\n",
    "        flipud=0.4, fliplr=0.5,\n",
    "        mosaic=1.0, mixup=0.15, copy_paste=0.15,\n",
    "        # ── Loss weights: focus on hard classes ───────────────────────────────\n",
    "        cls=2.0,        # focal-style: forces model to focus on water confusion\n",
    "        box=7.5,        # strong box regression\n",
    "        dfl=1.5,\n",
    "        # ── Class weights: penalise missing water more ────────────────────────\n",
    "        # Note: YOLO does not have direct class_weights param but cls loss\n",
    "        # scaling + augmentation balance achieves the same effect\n",
    "        # ── Output ────────────────────────────────────────────────────────────\n",
    "        project='/content/runs',\n",
    "        name=f'fold_{fold_idx}',\n",
    "        save=True, plots=True, verbose=False\n",
    "    )\n",
    "\n",
    "    # ── Evaluate this fold ────────────────────────────────────────────────────\n",
    "    best_w = f'/content/runs/fold_{fold_idx}/weights/best.pt'\n",
    "    fold_model = YOLO(best_w)\n",
    "    metrics = fold_model.val(data=yaml_path, split='val',\n",
    "                              imgsz=IMGSZ, conf=0.35, iou=0.5, verbose=False)\n",
    "    mAP50 = metrics.box.map50\n",
    "    fold_results.append((fold_idx, mAP50, best_w))\n",
    "    print(f'  Fold {fold_idx+1} mAP@0.5 = {mAP50:.4f}')\n",
    "\n",
    "# ── Summary ───────────────────────────────────────────────────────────────────\n",
    "print('\\n' + '='*60)\n",
    "print('K-FOLD CROSS VALIDATION RESULTS')\n",
    "print('='*60)\n",
    "maps = [r[1] for r in fold_results]\n",
    "for fold_idx, mAP50, _ in fold_results:\n",
    "    print(f'  Fold {fold_idx+1}: mAP@0.5 = {mAP50:.4f}')\n",
    "print(f'  Mean  : {np.mean(maps):.4f} ± {np.std(maps):.4f}')\n",
    "best_fold = fold_results[np.argmax(maps)]\n",
    "print(f'  Best  : Fold {best_fold[0]+1} → {best_fold[1]:.4f}')\n",
    "print('='*60)\n",
    "\n",
    "# ── Select best fold model ────────────────────────────────────────────────────\n",
    "BEST_WEIGHTS = best_fold[2]\n",
    "best_model   = YOLO(BEST_WEIGHTS)\n",
    "print(f'\\n✅ Best model: {BEST_WEIGHTS}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 8 — K-Fold Results & Training Curves"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── K-Fold bar chart ──────────────────────────────────────────────────────────\n",
    "fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n",
    "\n",
    "fold_labels = [f'Fold {i+1}' for i, _, _ in fold_results]\n",
    "fold_maps   = [m for _, m, _ in fold_results]\n",
    "colors = ['green' if m == max(fold_maps) else 'steelblue' for m in fold_maps]\n",
    "\n",
    "axes[0].bar(fold_labels, fold_maps, color=colors, edgecolor='black', linewidth=0.8)\n",
    "axes[0].axhline(np.mean(fold_maps), color='red', linestyle='--', linewidth=2,\n",
    "                label=f'Mean = {np.mean(fold_maps):.3f}')\n",
    "axes[0].set_ylim(0, 1.05)\n",
    "axes[0].set_ylabel('mAP@0.5')\n",
    "axes[0].set_title('K-Fold Cross Validation — mAP@0.5 per Fold', fontweight='bold')\n",
    "axes[0].legend()\n",
    "for i, (v, c) in enumerate(zip(fold_maps, colors)):\n",
    "    axes[0].text(i, v + 0.01, f'{v:.3f}', ha='center', fontsize=10, fontweight='bold')\n",
    "\n",
    "# ── Best fold training curves ─────────────────────────────────────────────────\n",
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "csv_path = f'/content/runs/fold_{best_fold_idx}/results.csv'\n",
    "df = pd.read_csv(csv_path)\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "def find_col(df, candidates):\n",
    "    for c in candidates:\n",
    "        if c in df.columns: return c\n",
    "    return None\n",
    "\n",
    "epoch_col = find_col(df, ['epoch', 'Epoch'])\n",
    "map_col   = find_col(df, ['metrics/mAP50(B)', 'metrics/mAP50', 'metrics/mAP_0.5'])\n",
    "rec_col   = find_col(df, ['metrics/recall(B)', 'metrics/recall'])\n",
    "\n",
    "if map_col and rec_col:\n",
    "    axes[1].plot(df[epoch_col], df[map_col], color='green',  linewidth=2, label='mAP@0.5')\n",
    "    axes[1].plot(df[epoch_col], df[rec_col], color='teal',   linewidth=2, label='Recall')\n",
    "    axes[1].set_ylim(0, 1.05)\n",
    "    axes[1].set_xlabel('Epoch')\n",
    "    axes[1].set_title(f'Best Fold ({best_fold_idx+1}) Training Progress', fontweight='bold')\n",
    "    axes[1].legend()\n",
    "    axes[1].grid(alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('/content/kfold_results.png', dpi=150)\n",
    "plt.show()\n",
    "\n",
    "# ── Full training curves (best fold) ──────────────────────────────────────────\n",
    "plots_cfg = [\n",
    "    (find_col(df, ['train/box_loss', 'train/cls_loss']), 'Train Box Loss', 'blue'),\n",
    "    (find_col(df, ['val/box_loss',   'val/cls_loss'  ]), 'Val Box Loss',   'orange'),\n",
    "    (map_col,                                             'mAP@0.5',       'green'),\n",
    "    (find_col(df, ['metrics/mAP50-95(B)', 'metrics/mAP50-95']), 'mAP@0.5:0.95', 'purple'),\n",
    "    (find_col(df, ['metrics/precision(B)', 'metrics/precision']), 'Precision',   'red'),\n",
    "    (rec_col,                                             'Recall',         'teal'),\n",
    "]\n",
    "fig2, axes2 = plt.subplots(2, 3, figsize=(18, 10))\n",
    "for ax, (col, title, color) in zip(axes2.flatten(), plots_cfg):\n",
    "    if col and col in df.columns:\n",
    "        ax.plot(df[epoch_col], df[col], color=color, linewidth=2)\n",
    "        final = df[col].iloc[-1]\n",
    "        ax.annotate(f'{final:.3f}', xy=(df[epoch_col].iloc[-1], final),\n",
    "                    fontsize=9, color=color, fontweight='bold',\n",
    "                    xytext=(-30, 8), textcoords='offset points')\n",
    "        ax.set_title(title, fontweight='bold')\n",
    "        ax.set_xlabel('Epoch'); ax.grid(alpha=0.3)\n",
    "    else:\n",
    "        ax.set_title(f'{title} (not found)', color='gray'); ax.grid(alpha=0.3)\n",
    "plt.suptitle(f'Training Curves — Best Fold {best_fold_idx+1}', fontsize=14, fontweight='bold')\n",
    "plt.tight_layout()\n",
    "plt.savefig('/content/curves.png', dpi=150)\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 9 — Final Evaluation (Best Fold)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "EVAL_YAML = f'/content/fold_{best_fold_idx}/dataset.yaml'\n",
    "\n",
    "metrics = best_model.val(data=EVAL_YAML, split='val',\n",
    "                          imgsz=IMGSZ, conf=0.35, iou=0.5, plots=True)\n",
    "\n",
    "CLASS_NAMES_LIST = ['defect', 'label', 'water']\n",
    "TARGETS = {'defect': 0.95, 'label': 0.93, 'water': 0.88}\n",
    "\n",
    "print('\\n' + '='*50)\n",
    "print('FINAL MODEL PERFORMANCE')\n",
    "print('='*50)\n",
    "print(f'  mAP@0.5      : {metrics.box.map50:.4f}')\n",
    "print(f'  mAP@0.5:0.95 : {metrics.box.map:.4f}')\n",
    "print(f'  Precision    : {metrics.box.mp:.4f}')\n",
    "print(f'  Recall       : {metrics.box.mr:.4f}')\n",
    "\n",
    "if hasattr(metrics.box, 'ap_class_index'):\n",
    "    print('\\n  Per-class AP@0.5:')\n",
    "    for idx, ap in zip(metrics.box.ap_class_index, metrics.box.ap50):\n",
    "        name   = CLASS_NAMES_LIST[idx]\n",
    "        target = TARGETS.get(name, 0.90)\n",
    "        flag   = 'OK' if ap >= target else 'below target'\n",
    "        print(f'    {name:8s}: {ap:.4f}  (target ≥ {target})  {flag}')\n",
    "\n",
    "print('='*50)\n",
    "if metrics.box.map50 >= 0.93:\n",
    "    print(' Excellent — top-grade production model!')\n",
    "elif metrics.box.map50 >= 0.90:\n",
    "    print(' Production ready!')\n",
    "elif metrics.box.map50 >= 0.85:\n",
    "    print(' Good — minor improvements possible')\n",
    "else:\n",
    "    print(' Needs improvement')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 10 — Anti-Bias Check\n",
    "> Detects if the model is over-predicting any class (bias).\n",
    "> Run this before deployment. A biased model can cause false factory stops."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "val_imgs   = sorted(glob.glob(f'/content/fold_{best_fold_idx}/images/val/*.jpg'))\n",
    "val_labels = f'/content/fold_{best_fold_idx}/labels/val'\n",
    "CLASS_NAMES_LIST = ['defect', 'label', 'water']\n",
    "\n",
    "gt_counts   = Counter()\n",
    "pred_counts = Counter()\n",
    "miss_counts = Counter()   # GT boxes not detected\n",
    "fp_counts   = Counter()   # Predicted boxes with no GT match\n",
    "\n",
    "iou_threshold = 0.5\n",
    "conf_thresh   = 0.35\n",
    "\n",
    "print('Running anti-bias analysis on validation set...')\n",
    "for img_path in val_imgs:\n",
    "    stem     = os.path.splitext(os.path.basename(img_path))[0]\n",
    "    lbl_path = f'{val_labels}/{stem}.txt'\n",
    "    gt_boxes = []\n",
    "    if os.path.exists(lbl_path):\n",
    "        with open(lbl_path) as f:\n",
    "            for line in f:\n",
    "                p = line.strip().split()\n",
    "                if len(p) == 5:\n",
    "                    gt_boxes.append([int(p[0])] + [float(x) for x in p[1:]])\n",
    "                    gt_counts[int(p[0])] += 1\n",
    "\n",
    "    result = best_model.predict(source=img_path, conf=conf_thresh,\n",
    "                                iou=0.45, imgsz=IMGSZ, verbose=False)[0]\n",
    "    pred_boxes = []\n",
    "    if result.boxes and len(result.boxes) > 0:\n",
    "        clses = result.boxes.cls.cpu().numpy().astype(int)\n",
    "        for cid in clses:\n",
    "            pred_counts[cid] += 1\n",
    "        # Simple IoU matching (approximate)\n",
    "        pred_xyxy = result.boxes.xyxy.cpu().numpy()\n",
    "        img = cv2.imread(img_path)\n",
    "        ih, iw = img.shape[:2]\n",
    "        for gt in gt_boxes:\n",
    "            gcls, gcx, gcy, gw, gh = gt\n",
    "            gx1 = (gcx - gw/2) * iw; gy1 = (gcy - gh/2) * ih\n",
    "            gx2 = (gcx + gw/2) * iw; gy2 = (gcy + gh/2) * ih\n",
    "            matched = False\n",
    "            for px1, py1, px2, py2 in pred_xyxy:\n",
    "                ix1 = max(gx1, px1); iy1 = max(gy1, py1)\n",
    "                ix2 = min(gx2, px2); iy2 = min(gy2, py2)\n",
    "                inter = max(0, ix2-ix1) * max(0, iy2-iy1)\n",
    "                union = (gx2-gx1)*(gy2-gy1) + (px2-px1)*(py2-py1) - inter\n",
    "                if union > 0 and inter/union >= iou_threshold:\n",
    "                    matched = True; break\n",
    "            if not matched:\n",
    "                miss_counts[gcls] += 1\n",
    "\n",
    "# ── Report ─────────────────────────────────────────────────────────────────────\n",
    "print('\\n' + '═'*55)\n",
    "print('ANTI-BIAS REPORT')\n",
    "print('═'*55)\n",
    "print(f'  {\"Class\":10s}  {\"GT boxes\":>10s}  {\"Predicted\":>10s}  {\"Missed\":>8s}  {\"Bias?\":>8s}')\n",
    "print(f'  {\"-\"*10}  {\"-\"*10}  {\"-\"*10}  {\"-\"*8}  {\"-\"*8}')\n",
    "bias_detected = False\n",
    "for cid in range(3):\n",
    "    name = CLASS_NAMES_LIST[cid]\n",
    "    gt   = gt_counts.get(cid, 0)\n",
    "    pred = pred_counts.get(cid, 0)\n",
    "    miss = miss_counts.get(cid, 0)\n",
    "    ratio = pred / gt if gt > 0 else 0\n",
    "    if ratio > 1.5:\n",
    "        bias = 'OVER'\n",
    "        bias_detected = True\n",
    "    elif ratio < 0.6:\n",
    "        bias = 'UNDER'\n",
    "        bias_detected = True\n",
    "    else:\n",
    "        bias = 'OK'\n",
    "    print(f'  {name:10s}  {gt:>10d}  {pred:>10d}  {miss:>8d}  {bias:>8s}')\n",
    "print('═'*55)\n",
    "if bias_detected:\n",
    "    print('  Bias detected! See tips below.')\n",
    "    print('  Over-prediction → raise PER_CLASS_CONF for that class')\n",
    "    print('  Under-prediction → lower PER_CLASS_CONF or add more data')\n",
    "else:\n",
    "    print('  No significant bias detected — model is balanced!')\n",
    "print()\n",
    "\n",
    "# ── Calibrated threshold recommendation ───────────────────────────────────────\n",
    "print('CALIBRATED THRESHOLD RECOMMENDATION:')\n",
    "print('  Based on bias analysis, use these per-class thresholds:')\n",
    "rec_thresh = {}\n",
    "for cid in range(3):\n",
    "    name = CLASS_NAMES_LIST[cid]\n",
    "    gt   = gt_counts.get(cid, 0)\n",
    "    pred = pred_counts.get(cid, 0)\n",
    "    miss = miss_counts.get(cid, 0)\n",
    "    if gt == 0: rec_thresh[cid] = 0.45; continue\n",
    "    miss_rate = miss / gt\n",
    "    if miss_rate > 0.20:\n",
    "        t = 0.30   # missing too many → lower threshold\n",
    "    elif pred / gt > 1.4:\n",
    "        t = 0.55   # over-predicting → raise threshold\n",
    "    else:\n",
    "        t = 0.45   # balanced\n",
    "    rec_thresh[cid] = t\n",
    "    print(f'  {name:8s}: {t:.2f}  (miss rate: {miss_rate:.0%})')\n",
    "\n",
    "# Save recommended thresholds for predict_single\n",
    "import json as _json\n",
    "with open('/content/recommended_thresholds.json', 'w') as _f:\n",
    "    _json.dump(rec_thresh, _f)\n",
    "print('\\n  Thresholds saved to /content/recommended_thresholds.json')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 11 — Predict on Validation Images"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "CLASS_NAMES   = ['defect', 'label', 'water']\n",
    "\n",
    "test_images = sorted(glob.glob(f'/content/fold_{best_fold_idx}/images/val/*.jpg'))[:8]\n",
    "preds = best_model.predict(source=test_images, conf=0.35, iou=0.45, imgsz=IMGSZ)\n",
    "fig, axes = plt.subplots(2, 4, figsize=(22, 10))\n",
    "axes = axes.flatten()\n",
    "for i, result in enumerate(preds[:8]):\n",
    "    axes[i].imshow(cv2.cvtColor(result.plot(), cv2.COLOR_BGR2RGB))\n",
    "    if result.boxes and len(result.boxes.conf) > 0:\n",
    "        c   = result.boxes.conf.cpu().numpy()\n",
    "        cls = result.boxes.cls.cpu().numpy().astype(int)\n",
    "        summary = '  '.join([f'{CLASS_NAMES[k]}:{v:.0%}' for k,v in zip(cls,c)])\n",
    "        axes[i].set_title(summary, fontsize=8, color='red', fontweight='bold')\n",
    "    else:\n",
    "        axes[i].set_title('No detection', fontsize=9, color='green')\n",
    "    axes[i].axis('off')\n",
    "plt.tight_layout(); plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 12 — Live Demo (Calibrated Per-Class Thresholds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json as _json, os as _os\n",
    "\n",
    "CLASS_NAMES = ['defect', 'label', 'water']\n",
    "\n",
    "# ── Load recommended thresholds from anti-bias step (or set manually) ─────────\n",
    "_thresh_file = '/content/recommended_thresholds.json'\n",
    "if _os.path.exists(_thresh_file):\n",
    "    _raw = _json.load(open(_thresh_file))\n",
    "    PER_CLASS_CONF = {int(k): v for k, v in _raw.items()}\n",
    "    print(f'Loaded calibrated thresholds: {PER_CLASS_CONF}')\n",
    "else:\n",
    "    PER_CLASS_CONF = {0: 0.50, 1: 0.50, 2: 0.35}\n",
    "    print(f'Using default thresholds: {PER_CLASS_CONF}')\n",
    "\n",
    "IOU_THRESHOLD = 0.40\n",
    "\n",
    "# ── Override manually if needed ───────────────────────────────────────────────\n",
    "# PER_CLASS_CONF = {0: 0.50, 1: 0.50, 2: 0.30}  # aggressive water\n",
    "# PER_CLASS_CONF = {0: 0.55, 1: 0.55, 2: 0.40}  # conservative\n",
    "\n",
    "def predict_single(image_path, iou=IOU_THRESHOLD, per_class_conf=PER_CLASS_CONF):\n",
    "    \"\"\"Predict with TTA + per-class calibrated confidence filtering.\"\"\"\n",
    "    result = best_model.predict(\n",
    "        source=image_path,\n",
    "        conf=min(per_class_conf.values()),  # low gate, filter below\n",
    "        iou=iou,\n",
    "        imgsz=IMGSZ,\n",
    "        augment=True   # TTA: test-time augmentation for higher confidence\n",
    "    )[0]\n",
    "\n",
    "    # ── Per-class confidence filter ────────────────────────────────────────────\n",
    "    if result.boxes and len(result.boxes) > 0:\n",
    "        confs_all = result.boxes.conf.cpu().numpy()\n",
    "        clses_all = result.boxes.cls.cpu().numpy().astype(int)\n",
    "        keep = [i for i, (c, k) in enumerate(zip(confs_all, clses_all))\n",
    "                if c >= per_class_conf.get(k, 0.45)]\n",
    "        if len(keep) < len(confs_all):\n",
    "            result.boxes = result.boxes[keep]\n",
    "\n",
    "    plt.figure(figsize=(11, 8))\n",
    "    plt.imshow(cv2.cvtColor(result.plot(), cv2.COLOR_BGR2RGB))\n",
    "\n",
    "    if result.boxes and len(result.boxes) > 0:\n",
    "        confs = result.boxes.conf.cpu().numpy()\n",
    "        clses = result.boxes.cls.cpu().numpy().astype(int)\n",
    "        title = (f'{len(confs)} detection(s)  |  '\n",
    "                 f'avg: {confs.mean():.1%}  |  max: {confs.max():.1%}')\n",
    "        plt.title(title, color='red', fontsize=13, fontweight='bold')\n",
    "        print('\\n── Detection Report ──────────────────────────')\n",
    "        counts = Counter(clses)\n",
    "        for cid, cnt in sorted(counts.items()):\n",
    "            cc = confs[clses == cid]\n",
    "            print(f'  {CLASS_NAMES[cid]:8s} ×{cnt}  '\n",
    "                  f'avg:{cc.mean():.1%}  max:{cc.max():.1%}  '\n",
    "                  f'[thresh:{per_class_conf.get(cid,0.45):.0%}]')\n",
    "        print('──────────────────────────────────────────────')\n",
    "        for j, (c, cid) in enumerate(zip(confs, clses)):\n",
    "            print(f'  [{j+1}] {CLASS_NAMES[cid]:8s}  {c:.1%}')\n",
    "    else:\n",
    "        plt.title('No Detection Above Threshold',\n",
    "                  color='green', fontsize=13, fontweight='bold')\n",
    "        print(f'No detections. Try lowering PER_CLASS_CONF values.')\n",
    "    plt.axis('off'); plt.tight_layout(); plt.show()\n",
    "\n",
    "# ── Test on a validation sample ───────────────────────────────────────────────\n",
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "sample = sorted(glob.glob(f'/content/fold_{best_fold_idx}/images/val/*.jpg'))[0]\n",
    "predict_single(sample)\n",
    "\n",
    "# ── Upload your own image ─────────────────────────────────────────────────────\n",
    "# u = files.upload(); predict_single(list(u.keys())[0])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 13 — Batch Live Demo (Upload Multiple Images)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "CLASS_NAMES = ['defect', 'label', 'water']\n",
    "\n",
    "print('Upload one or more images...')\n",
    "uploaded_batch = files.upload()\n",
    "\n",
    "all_results = []\n",
    "for fname in uploaded_batch:\n",
    "    r = best_model.predict(\n",
    "        source=fname,\n",
    "        conf=min(PER_CLASS_CONF.values()),\n",
    "        iou=IOU_THRESHOLD, imgsz=IMGSZ, augment=True\n",
    "    )[0]\n",
    "    if r.boxes and len(r.boxes) > 0:\n",
    "        ca = r.boxes.conf.cpu().numpy()\n",
    "        ka = r.boxes.cls.cpu().numpy().astype(int)\n",
    "        keep = [i for i,(c,k) in enumerate(zip(ca,ka))\n",
    "                if c >= PER_CLASS_CONF.get(k, 0.45)]\n",
    "        if len(keep) < len(ca): r.boxes = r.boxes[keep]\n",
    "    all_results.append((fname, r))\n",
    "\n",
    "n = len(all_results)\n",
    "cols = min(3, n); rows = (n + cols - 1) // cols\n",
    "fig, axes = plt.subplots(rows, cols, figsize=(7*cols, 6*rows))\n",
    "axes_flat = axes.flatten() if n > 1 else [axes]\n",
    "\n",
    "print('\\n══ Batch Confidence Report ═══════════════════════')\n",
    "for ax, (fname, result) in zip(axes_flat, all_results):\n",
    "    ax.imshow(cv2.cvtColor(result.plot(), cv2.COLOR_BGR2RGB))\n",
    "    if result.boxes and len(result.boxes) > 0:\n",
    "        confs = result.boxes.conf.cpu().numpy()\n",
    "        clses = result.boxes.cls.cpu().numpy().astype(int)\n",
    "        summary = '  '.join([f'{CLASS_NAMES[k]}:{v:.0%}' for k,v in zip(clses,confs)])\n",
    "        ax.set_title(f'{os.path.basename(fname)}\\n{summary}',\n",
    "                     fontsize=8, color='red', fontweight='bold')\n",
    "        print(f'  {os.path.basename(fname)}: {summary}')\n",
    "    else:\n",
    "        ax.set_title(f'{os.path.basename(fname)}\\nNo Detection',\n",
    "                     fontsize=8, color='green')\n",
    "        print(f'  {os.path.basename(fname)}: No detection')\n",
    "    ax.axis('off')\n",
    "for ax in axes_flat[n:]: ax.axis('off')\n",
    "print('═══════════════════════════════════════════════════')\n",
    "plt.suptitle('Batch Results — defect | label | water', fontsize=13, fontweight='bold')\n",
    "plt.tight_layout(); plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 14 — Water vs Defect Confusion Diagnostic\n",
    "> Finds images where the model confuses water for defect or vice versa."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "val_imgs  = sorted(glob.glob(f'/content/fold_{best_fold_idx}/images/val/*.jpg'))\n",
    "val_lbls  = f'/content/fold_{best_fold_idx}/labels/val'\n",
    "CLASS_NAMES = ['defect', 'label', 'water']\n",
    "\n",
    "confusion_cases = []   # (img_path, gt_class, pred_class, conf)\n",
    "miss_counts = Counter()\n",
    "conf_counts = Counter()   # confused predictions\n",
    "\n",
    "for img_path in val_imgs:\n",
    "    stem     = os.path.splitext(os.path.basename(img_path))[0]\n",
    "    lbl_path = f'{val_lbls}/{stem}.txt'\n",
    "    gt_classes = []\n",
    "    if os.path.exists(lbl_path):\n",
    "        with open(lbl_path) as f:\n",
    "            for line in f:\n",
    "                p = line.strip().split()\n",
    "                if p: gt_classes.append(int(p[0]))\n",
    "    if not gt_classes: continue\n",
    "\n",
    "    result = best_model.predict(source=img_path, conf=0.25,\n",
    "                                iou=0.45, imgsz=IMGSZ, verbose=False)[0]\n",
    "    pred_classes = []\n",
    "    if result.boxes and len(result.boxes) > 0:\n",
    "        pred_classes = result.boxes.cls.cpu().numpy().astype(int).tolist()\n",
    "\n",
    "    gt_c   = Counter(gt_classes)\n",
    "    pred_c = Counter(pred_classes)\n",
    "\n",
    "    # Check for water GT but defect predicted (or vice versa)\n",
    "    if 2 in gt_c and 0 in pred_c and 2 not in pred_c:\n",
    "        confusion_cases.append((img_path, 'water→defect'))\n",
    "        conf_counts['water_as_defect'] += 1\n",
    "    if 0 in gt_c and 2 in pred_c and 0 not in pred_c:\n",
    "        confusion_cases.append((img_path, 'defect→water'))\n",
    "        conf_counts['defect_as_water'] += 1\n",
    "    for cid in range(3):\n",
    "        if cid in gt_c and cid not in pred_c:\n",
    "            miss_counts[cid] += gt_c[cid]\n",
    "\n",
    "print('══ Confusion & Miss Report ══════════════════')\n",
    "print(f'  water predicted as defect : {conf_counts[\"water_as_defect\"]} images')\n",
    "print(f'  defect predicted as water : {conf_counts[\"defect_as_water\"]} images')\n",
    "print()\n",
    "for cid, cnt in sorted(miss_counts.items()):\n",
    "    flag = 'NEED improvement' if cnt > 3 else 'OK'\n",
    "    print(f'  {CLASS_NAMES[cid]:8s} missed: {cnt} boxes  {flag}')\n",
    "print('═════════════════════════════════════════════')\n",
    "\n",
    "# ── Show worst confusion examples ────────────────────────────────────────────\n",
    "n_show = min(4, len(confusion_cases))\n",
    "if n_show > 0:\n",
    "    print(f'\\nShowing {n_show} confusion examples:')\n",
    "    fig, axes = plt.subplots(1, n_show, figsize=(6*n_show, 6))\n",
    "    if n_show == 1: axes = [axes]\n",
    "    for ax, (img_path, case_type) in zip(axes, confusion_cases[:n_show]):\n",
    "        result = best_model.predict(source=img_path, conf=0.25,\n",
    "                                    iou=0.45, imgsz=IMGSZ, verbose=False)[0]\n",
    "        ax.imshow(cv2.cvtColor(result.plot(), cv2.COLOR_BGR2RGB))\n",
    "        ax.set_title(f'Confusion: {case_type}', color='red', fontsize=10, fontweight='bold')\n",
    "        ax.axis('off')\n",
    "    plt.tight_layout(); plt.show()\n",
    "else:\n",
    "    print('No water↔defect confusion found!')\n",
    "\n",
    "print('\\nTips to reduce confusion:')\n",
    "print('  1. Add more diverse water images (different lighting, angles)')\n",
    "print('  2. Check water labels — some may be mislabeled as defect')\n",
    "print('  3. Raise water confidence: PER_CLASS_CONF[2] = 0.40')\n",
    "print('  4. Lower water confidence: PER_CLASS_CONF[2] = 0.25 (catch more)')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 15 — Export & Download"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "best_model.export(format='onnx', imgsz=IMGSZ, simplify=True)\n",
    "EXPORT = '/content/export_v4'\n",
    "os.makedirs(EXPORT, exist_ok=True)\n",
    "shutil.copy(BEST_WEIGHTS, f'{EXPORT}/best.pt')\n",
    "onnx_path = BEST_WEIGHTS.replace('best.pt', 'best.onnx')\n",
    "if os.path.exists(onnx_path):\n",
    "    shutil.copy(onnx_path, f'{EXPORT}/best.onnx')\n",
    "\n",
    "# Save YAML and thresholds\n",
    "best_fold_idx = fold_results[np.argmax([m for _, m, _ in fold_results])][0]\n",
    "shutil.copy(f'/content/fold_{best_fold_idx}/dataset.yaml', f'{EXPORT}/dataset.yaml')\n",
    "if os.path.exists('/content/recommended_thresholds.json'):\n",
    "    shutil.copy('/content/recommended_thresholds.json', f'{EXPORT}/thresholds.json')\n",
    "if os.path.exists('/content/kfold_results.png'):\n",
    "    shutil.copy('/content/kfold_results.png', f'{EXPORT}/kfold_results.png')\n",
    "\n",
    "# Save model info\n",
    "import json as _json\n",
    "info = {\n",
    "    'model': 'YOLO26s',\n",
    "    'imgsz': IMGSZ,\n",
    "    'classes': ['defect', 'label', 'water'],\n",
    "    'best_fold': best_fold_idx + 1,\n",
    "    'kfold_mean_map50': float(np.mean([m for _, m, _ in fold_results])),\n",
    "    'kfold_std_map50':  float(np.std( [m for _, m, _ in fold_results])),\n",
    "    'per_class_thresholds': PER_CLASS_CONF\n",
    "}\n",
    "with open(f'{EXPORT}/model_info.json', 'w') as f:\n",
    "    _json.dump(info, f, indent=2)\n",
    "print(_json.dumps(info, indent=2))\n",
    "\n",
    "shutil.make_archive('/content/cable_model_v4', 'zip', EXPORT)\n",
    "files.download('/content/cable_model_v4.zip')\n",
    "print('\\n Done! Model exported.')\n"
   ]
  }
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {
   "gpuType": "T4",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
